@hostname = {{$dotenv SERVER_DOMAIN}}
@port = {{$dotenv PORT}}
@host = http://{{hostname}}:{{port}}

###

GET {{host}}/pieces

###

POST {{host}}/pieces
content-type: application/json

{
  "name": "Name",
  "json": "[{\"value\": 10}]",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWVmZjgzMDA3MGM5NTdkOWEzODI4NTEiLCJpYXQiOjE2NDMxMTY1OTl9.LPjoMs1u59TQPnHMB5MqTpXRAdh4qkJ6DwW6F9KEgPM"
}

###

DELETE {{host}}/pieces/61ef3ed416a48c21611c5972

###

GET {{host}}/pieces/61ef3ed416a48c21611c5972
